name: Dummy Deploy Workflow

on:
  workflow_call:
    inputs:
      target-env:
        required: true
        type: string
      stage:
        required: true
        type: string
      region:
        required: true
        type: string
    secrets:
      DUMMY_SECRET:
        required: true
    

jobs:
  dummy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}
    steps:
      - name: Show input values
        run: |
          echo "Stage: ${{ inputs.stage }}"
          echo "Region: ${{ inputs.region }}"

      - name: Show secret value
        run: |
          echo "Dummy Secret: ${{ vars.DUMMY_SECRET }}"
          echo "Secret length: ${#MY_SECRET}"
