name: Deploy Dev (Dummy)

on:
  workflow_dispatch:

jobs:
  call-dummy:
    uses: ./.github/workflows/deploy.yml
    with:
      target-env: dev
    secrets: inherit
    permissions:
      id-token: write      
      contents: read
