name: Dummy Test Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Your name"
        required: true
        default: "World"
      environment:
        description: "Choose environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod
          - custom
      custom_value:
        description: "Enter custom value (only used if environment=custom)"
        required: false

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Mask custom input
        if: ${{ github.event.inputs.environment == 'custom' }}
        run: |
          echo "::add-mask::${{ github.event.inputs.custom_value }}"
          echo "CUSTOM_VALUE=${{ github.event.inputs.custom_value }}" >> $GITHUB_ENV

      - name: Print greeting
        run: |
          if [ "${{ github.event.inputs.environment }}" = "custom" ]; then
            echo "Hello ${{ github.event.inputs.name }}! You selected CUSTOM environment 🚀"
            echo "Custom value is safely stored in env but not shown in logs."
          else
            echo "Hello ${{ github.event.inputs.name }}! Deploying to ${{ github.event.inputs.environment }} 🚀"
          fi
