# name: Test Env Fileee

# on:
#   workflow_dispatch:
#     inputs:
#       additional_env_vars:
#         description: "Comma-separated extra env vars"
#         required: false

# jobs:
#   prepare-env:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Mask sensitive values
#         run: |
#          ADDITIONAL_ENV_VARS=$(jq -r '.inputs.additional_env_vars' $GITHUB_EVENT_PATH)
#          echo ::add-mask::$ADDITIONAL_ENV_VARS
#          echo ADDITIONAL_ENV_VARS=$ADDITIONAL_ENV_VARS >> $GITHUB_ENV


#       - name: Prepare env file
#         run: |
#           mkdir -p envs
#           # Start with env vars from secrets
#           printf "%s\n" "${{ vars.CUSTOM_ENV_VARS }}" > envs/.env
          
#           # Append/override with additional input vars
#           if [ -n "${{ env.ADDITIONAL_ENV_VARS }}" ]; then
#             echo "${{ env.ADDITIONAL_ENV_VARS }}" | tr ',' '\n' | sed '/^$/d' >> envs/.env
#           fi
          
#           # Deduplicate by keeping the last occurrence of a key
#           awk -F= '!seen[$1]++{line[NR]=$0; order[NR]=$1} {val[$1]=$0} END {for (i=1;i<=NR;i++) if (order[i] in val) {print val[order[i]]; delete val[order[i]]}}' envs/.env > envs/.env.tmp && mv envs/.env.tmp envs/.env

#       - name: Show final env file
#         run: cat envs/.env

name: Test Env File

on:
  workflow_dispatch:
    inputs:
      additional_env_vars:
        description: "Comma-separated extra env vars"
        required: false

jobs:
  prepare-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mask sensitive values
        run: |
          echo "::add-mask::${{ vars.CUSTOM_ENV_VARS }}"
          value="${{ github.event.inputs.additional_env_vars }}"
          echo "::add-mask::$value"
      - name: Prepare env file
        run: |
          mkdir -p envs
          # Start with env vars from secrets
          printf "%s\n" "${{ vars.CUSTOM_ENV_VARS }}" > envs/.env
          
          # Append/override with additional input vars
          if [ -n "${{ github.event.inputs.additional_env_vars }}" ]; then
            echo "${{ github.event.inputs.additional_env_vars }}" | tr ',' '\n' | sed '/^$/d' >> envs/.env
          fi
          
          # Deduplicate by keeping the last occurrence of a key
          awk -F= '!seen[$1]++{line[NR]=$0; order[NR]=$1} {val[$1]=$0} END {for (i=1;i<=NR;i++) if (order[i] in val) {print val[order[i]]; delete val[order[i]]}}' envs/.env > envs/.env.tmp && mv envs/.env.tmp envs/.env
      - name: Show final env file
        run: cat envs/.env
