name: Test Multi-Environment Deployment

on:
  workflow_dispatch:

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      envs: ${{ steps.set-matrix.outputs.envs }}
    steps:
      - name: Generate environment matrix from secret
        id: set-matrix
        run: |
          # convert comma-separated secret to JSON array
          JSON=$(echo "$DEPLOY_ENV_LIST" | sed 's/,/","/g')
          echo "envs=[\"$JSON\"]" >> $GITHUB_OUTPUT
        env:
          DEPLOY_ENV_LIST: ${{ secrets.DEPLOY_ENV_LIST }}

  deploy:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ${{ fromJSON(needs.prepare-matrix.outputs.envs) }}
    steps:
      - name: Print environment info
        run: |
          echo "=============================="
          echo "Simulating deploy to: ${{ matrix.environment }}"
          echo "MY_SECRET=${{ secrets.MY_SECRET }}"  # available in all envs
          echo "✅ Done with ${{ matrix.environment }}"
          echo "=============================="
