name: Deploy testing

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Where to deploy?"
        required: true
        default: "staging"
        type: choice
        options:
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print chosen environment
        run: echo "Environment selected:" ${{ github.event.inputs.environment }}
