name: lets test

on:
  workflow_dispatch:

  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   
      contents: read
      actions: read
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
